dependencies:
  - name: mysql
    version: "18.0127"
    repository: https://norwoodj.github.io/jchart-repository
  - name: rabbitmq
    version: "18.0127"
    repository: https://norwoodj.github.io/jchart-repository
  - name: web_service
    version: "18.0122"
    repository: https://norwoodj.github.io/jchart-repository
  - name: user_roles
    version: "17.1028"
    repository: https://norwoodj.github.io/jchart-repository
