
##
# MySQL settings
##
mysql:
  mysqlRootPasswordSecretName: hashbash-secrets
  mysqlRootPasswordSecretKey: hashbash.database.password

  nfs_volume:
    persistentVolumeStorageCapacity: 4Gi
    persistentVolumeNfsServer: rp3-smi-kbw-nfs-000
    persistentVolumeNfsPath: /nfs/hashbash
    persistentVolumeClaimStorageRequest: 4Gi

##
# Web Service settings
##
web_service:
  ingressName: hashbash-ingress
  ingressHostname: hashbash.johnmalcolmnorwood.com
  simple_service:
    serviceName: hashbash-web-service

##
# Hashbash server settings
##
deploymentName: hashbash-web-deployment
deploymentReplicas: 2
hashbashImage: jnorwood/hashbash-rpi_server
hashbashNginxImage: jnorwood/hashbash-rpi_nginx
hashbashHealthCheckEndpoint: /health
hashbashProbeInitialDelaySeconds: 300
hashbashProbePeriodSeconds: 300
hashbashProbeTimeoutSeconds: 10

##
# Hashbash consumer settings
##
consumerDeploymentName: hashbash-consumers
consumerDeploymentReplicas: 1
hashbashConsumersImage: jnorwood/hashbash-rpi_consumers
