kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.deploymentName }}
  labels:
{{- range .Values.web_service.simple_service.deploymentLabels }}
    {{ .key }}: {{ .value }}
{{- end }}

spec:
  replicas: {{ .Values.deploymentReplicas }}
  template:
    metadata:
      labels:
{{- range .Values.web_service.simple_service.deploymentLabels }}
        {{ .key }}: {{ .value }}
{{- end }}
    spec:
      containers:
        - name: hashbash-web
          image: {{ .Values.hashbashImage }}:{{ .Chart.Version }}
          imagePullPolicy: Always
          livenessProbe: &probe
            initialDelaySeconds: {{ .Values.hashbashInitialProbeDelaySeconds }}
            httpGet:
              port: http
              path: {{ .Values.hashbashHealthCheckEndpoint }}
          readinessProbe: *probe
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: RPI
