kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hashbash-mysql-deployment
  namespace: hashbash
spec:
  template:
    metadata:
      labels:
        role: mysql
    spec:
      containers:
        - name: mysql
          image: hypriot/rpi-mysql:5.5
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: hashbash-mysql-volume
              mountPath: /var/lib/mysql
      volumes:
          - name: hashbash-mysql-volume
            persistentVolumeClaim:
              claimName: hashbash-mysql-pv-claim

