kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hashbash-mysql-pv-claim
  namespace: hashbash
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: hashbash
