kind: PersistentVolume
apiVersion: v1
metadata:
  name: hashbash-mysql-pv
  labels:
    app: hashbash
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/hashbash
    server: rp3-smi-kbw-nfs-000
