kind: Service
apiVersion: v1
metadata:
  name: hashbash-web-service
  namespace: hashbash
spec:
  selector:
    role: hashbash-web-service
  ports:
    - name: http
      port: 80
      targetPort: http

